USE ULHT_DB26;
GO

-- EXERCICIOS DA AULA (1-10)
SELECT 'Olá, SQL' AS mensagem;

SELECT
    2+3 as soma,
    10*4 as produto,
    9.0/2 as divisão;

SELECT
    DB_NAME() as base_atual,
    GETDATE() as agora;

SELECT TOP 5 * FROM HR.EMPLOYEES;

SELECT TOP 5 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
 FROM HR.EMPLOYEES;


SELECT 'Estou pronto para SQL' as estado;

SELECT 3 * 12.5 AS RESULTADO;

SELECT TOP 5 DEPARTMENT_ID FROM HR.EMPLOYEES


SELECT TOP 10 
    EMPLOYEE_ID,
    FIRST_NAME,
    LAST_NAME
FROM HR.EMPLOYEES;

SELECT TOP 10 
    FIRST_NAME,
    LAST_NAME,
    EMAIL,
    PHONE_NUMBER
FROM HR.EMPLOYEES;

SELECT
    JOB_ID,
    JOB_TITLE,
    MIN_SALARY,
    MAX_SALARY
FROM HR.JOBS;

SELECT TOP 10
    DEPARTMENT_ID,
    DEPARTMENT_NAME,
    LOCATION_ID
FROM HR.DEPARTMENTS;


SELECT TOP 10
    EMPLOYEE_ID,
    SALARY,
    SALARY * 12 AS SALARIO_ANUAL
FROM HR.EMPLOYEES;

SELECT
    FIRST_NAME + ' ' + LAST_NAME AS NOME_COMPLETO
FROM HR.EMPLOYEES;

