USE ULHT_DB26;
GO

SELECT ORDINAL_POSITION,
COLUMN_NAME,
DATA_TYPE,
IS_NULLABLE 
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR'
AND TABLE_NAME = 'EMPLOYEES'
ORDER BY ORDINAL_POSITION;


DROP TABLE IF EXISTS dbo.AP02_LAB;
GO
CREATE TABLE dbo.AP02_LAB (
id INT PRIMARY KEY,
nome VARCHAR(60) NOT NULL,
cidade VARCHAR(40) NULL,
pontos INT NOT NULL DEFAULT 0,
ativo BIT NOT NULL DEFAULT 1
);
GO

INSERT INTO dbo.AP02_LAB
(id, nome, cidade, pontos, ativo)
VALUES
(101, 'Ana', 'Lisboa', 10, 1);

SELECT * FROM dbo.AP02_LAB WHERE ID = 101;

UPDATE dbo.AP02_LAB
SET pontos = pontos + 5
WHERE id = 101;

SELECT * FROM dbo.AP02_LAB WHERE ID = 101;

INSERT INTO DBO.AP02_LAB
(ID, NOME, CIDADE, PONTOS, ATIVO)
VALUES
(103, 'Jorge', 'Porto', 10, 1);

SELECT * FROM DBO.AP02_LAB WHERE ID=103;

DELETE FROM DBO.AP02_LAB WHERE ID = 101;

SELECT * FROM DBO.AP02_LAB WHERE ID=103;

BEGIN TRANSACTION;
UPDATE dbo.AP02_LAB
SET pontos = pontos + 100
WHERE id = 101;

SELECT * FROM DBO.AP02_LAB;

COMMIT;

BEGIN TRANSACTION;
UPDATE dbo.AP02_LAB
SET pontos = pontos + 100
WHERE id = 101;

SELECT * FROM DBO.AP02_LAB;

ROLLBACK;

SELECT * FROM DBO.AP02_LAB;

--1 
SELECT DB_NAME() AS Atual_DB;

--2
SELECT * FROM INFORMATION_SCHEMA.TABLES 
ORDER BY TABLE_NAME ASC;

--4
SELECT ORDINAL_POSITION,
COLUMN_NAME,
DATA_TYPE,
IS_NULLABLE
FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA = 'HR'
AND TABLE_NAME = 'EMPLOYEES'
ORDER BY ORDINAL_POSITION;

--5
SELECT TOP 5 * FROM HR.EMPLOYEES
ORDER BY EMPLOYEE_ID ASC;

--6
SELECT TOP 10 
    EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES

--7
SELECT EMPLOYEE_ID,SALARY 
FROM HR.EMPLOYEES WHERE SALARY > 10000
ORDER BY EMPLOYEE_ID ASC;

--8
SELECT EMPLOYEE_ID, FIRST_NAME, DEPARTMENT_ID
FROM HR.EMPLOYEES
WHERE DEPARTMENT_ID IN (50, 80)

--9
SELECT TOP 10 EMPLOYEE_ID, FIRST_NAME, LAST_NAME, SALARY
FROM HR.EMPLOYEES 
ORDER BY SALARY DESC , EMPLOYEE_ID DESC;

--10
SELECT * FROM DBO.AP02_LAB

--11
INSERT INTO DBO.AP02_LAB
(ID, NOME, CIDADE, PONTOS, ATIVO)
VALUES (101, 'Ana', 'Lisboa', 10, 1);

--12
INSERT INTO DBO.AP02_LAB
(ID, NOME, CIDADE, PONTOS, ATIVO)
VALUES (102, 'Bruno', 'Porto', 10, 1), 
(103, 'Carla', 'Braga', 10, 1);

--13
UPDATE DBO.AP02_LAB SET PONTOS = PONTOS + 5
WHERE ID = 101;

--14
UPDATE DBO.AP02_LAB SET CIDADE = NULL
WHERE ID = 102;

--15
DELETE FROM DBO.AP02_LAB WHERE ID = 103;